#include <stdio.h>
#include "C:\Users\naglaa\Desktop\ASU\2nd ECE\2nd Term\Embedded Systems\Embedded Project\tm4c123gh6pm.h"

void SystemInit(){}
void RGBLED_Init ()
{
SYSCTL_RCGCGPIO_R |= 0x2F;
while ((SYSCTL_PRGPIO_R&0x2F) == 0){};
	
GPIO_PORTA_LOCK_R = 0x4C4F434B;
GPIO_PORTB_LOCK_R = 0x4C4F434B;
GPIO_PORTC_LOCK_R = 0x4C4F434B;
GPIO_PORTD_LOCK_R = 0x4C4F434B;
GPIO_PORTF_LOCK_R = 0x4C4F434B;
GPIO_PORTA_CR_R |= 0x1C;
GPIO_PORTB_CR_R |= 0x48;
GPIO_PORTC_CR_R |= 0xF0;
GPIO_PORTD_CR_R |= 0xC0;
GPIO_PORTF_CR_R |= 0x0E;
GPIO_PORTA_DIR_R |= 0x1C;
GPIO_PORTB_DIR_R |= 0x48;
GPIO_PORTC_DIR_R |= 0xF0;
GPIO_PORTD_DIR_R |= 0xC0;
GPIO_PORTF_DIR_R |= 0x0E;
GPIO_PORTA_DEN_R |= 0x1C;
GPIO_PORTB_DEN_R |= 0x48;
GPIO_PORTC_DEN_R |= 0xF0;
GPIO_PORTD_DEN_R |= 0xC0;
GPIO_PORTF_DEN_R |= 0x0E;
GPIO_PORTA_AMSEL_R &= ~0x1C;
GPIO_PORTB_AMSEL_R &= ~0x48;
GPIO_PORTC_AMSEL_R &= ~0xF0;
GPIO_PORTD_AMSEL_R &= ~0xC0;
GPIO_PORTF_AMSEL_R &= ~0x0E;
GPIO_PORTA_AFSEL_R &= ~0x1C;
GPIO_PORTB_AFSEL_R &= ~0x48;
GPIO_PORTC_AFSEL_R &= ~0xF0;
GPIO_PORTD_AFSEL_R &= ~0xC0;
GPIO_PORTF_AFSEL_R &= ~0x0E;
GPIO_PORTA_PCTL_R &= ~0x000FFF00;
GPIO_PORTB_PCTL_R &= ~0xF00F000;
GPIO_PORTC_PCTL_R &= ~0xFFFF0000;
GPIO_PORTD_PCTL_R &= ~0xFF000000;
GPIO_PORTF_PCTL_R &= ~0x0000FFF0;
GPIO_PORTA_DATA_R &= ~0x1C;
GPIO_PORTB_DATA_R &= ~0x48;
GPIO_PORTC_DATA_R &= ~0xF0;
GPIO_PORTD_DATA_R &= ~0xC0;
GPIO_PORTF_DATA_R &= ~0x0E;

}

int main()
{
	
}
